#!/usr/bin/ksh

# Sat Aug 15 13:33:59 CEST 2015

export DISPLAY AWK STATSDIR PEERSTATS SELDATE CONF YEAR MINARGS TMPIPADDR SEDARG LIST STERM TITLE YLABEL HOSTN MYADDR

AWK=gawk
YEAR=`TZ=GMT date '+%Y'`
DEBUG=n
MINARGS=1
TMPIPADDR=/tmp/...tmpipaddr.$$
LIST=/tmp/erg.dat.$$
STERM="set term x11 persist"

thisusage(){
    echo
    echo "show NTP available peers as graph  - v 2015 08 16 "
    echo "  author: ntpgraph@ma.yer.at "
    echo
    echo "usage: $0 [ -D ] [ -f IMG ] DATE "
    echo "       date is MMDD in year $YEAR or YYYYMMDD or . ( . is today ) "
    echo "       -f IMG      - output to file - IMG can be jpeg, png, ... "
    echo "       -D          - debug "
    echo
    exit 1
}

# check the arguments
# go at least 1 time into the loop / there is no do until
do_once=1
while test $# -gt $MINARGS -o do_once -eq 1
  do
    do_once=0
    case $1 in
      -D ) DEBUG=y ; shift ;;
      -f ) FILE="set output \"plot_$$.$2\" "
           STERM="set terminal $2 size 800,500"
           LINEWIDTH=1
           echo $FILE ; shift ; shift ;;
      -* ) thisusage ; exit 1 ;;
    esac
    if test $# -lt $MINARGS
      then
        thisusage
        exit 1
    fi
  done


if test $# -eq 1
  then
    MDATE=$1
  else
    thisusage
    exit 1
fi


# very rudimentary check of date
case "$MDATE" in
  [0-9\?][0-9\?][0-9\?][0-9\?] )
        SELDATE=$YEAR$MDATE ;;
  [12][90][0-9\?][0-9\?][0-9\?][0-9\?][0-9\?][0-9\?] )
        SELDATE=$MDATE ;;
  \. )  SELDATE=`TZ=GMT date +%Y%m%d` ;;
  * )   echo $0: wrong date format - must be MMDD or . 1>&2
        thisusage
        exit 1
        ;;
esac

if test -z "$FILE"
  then
    # check if DISPLAY is set ?
    case "$DISPLAY" in
      localhost:* ) ;;
      "" )  echo '$DISPLAY not set' ; exit 1 ;;
      * ) ;;
    esac
fi

# check if gawk is available
type $AWK > /dev/null
if test $? -ne 0
  then
    echo try to install $AWK
    echo if not available try a symlink to awk or change this script
    exit 1
fi

# check where the conf file is located
CONF=N
if test -f /etc/ntp.conf
  then
    CONF=/etc/ntp.conf
fi
if test -f /etc/inet/ntp.conf
  then
    CONF=/etc/inet/ntp.conf
fi
if test $CONF = N
  then
    echo $0: ntp.conf not found
    exit 1
fi

# look what is statsdir directory and peerstats file defined
# awk is needed for solaris to strip off the leading blanks
STATSDIR=`grep statsdir $CONF | grep -v '^#' | tr '""' '  ' | head -1 | $AWK '{ print ( $2 ) }'`
PEERSTATS=`grep filegen $CONF | grep peerstats | grep -v '^#' | head -1 | $AWK '{ print ( $4 ) }'`
if test "$DEBUG" == y
  then
    echo CONF $CONF
    echo STATSDIR $STATSDIR PEERSTATS $PEERSTATS.$SELDATE
    echo TMPIPADDR $TMPIPADDR
fi

if test ! -f $STATSDIR/${PEERSTATS}.$SELDATE
  then
    echo $0: file $STATSDIR/${PEERSTATS}.$SELDATE not found
    exit 1
fi

cat $STATSDIR/${PEERSTATS}.$SELDATE | $AWK '{ print ( $3 ) }' | sort -u | $AWK '{ print ( $1 , NR ) }' > $TMPIPADDR
# max ip found + 1 
YRANGE=`wc -l $TMPIPADDR | $AWK '{ print ( "[0.8:" $1 + 1 "]" ) }'`
TITLE=`cat $TMPIPADDR  | $AWK '{ print ( $2 ":" , $1 ) }' | tr "\n" " "`
MYADDR=`ifconfig -a | grep inet | egrep -v '::1/128|127.0.0.1|inet6' | head -1 | $AWK '{ print $2 }'`
HOSTN=`hostname`

# replace IP address by index number 
SEDARG=`cat $TMPIPADDR | $AWK '{ print ( "-e s/" $1 "/" $2 "/" ) }'` 

# first host has number 1 
# for peer status word see https://www.eecis.udel.edu/~mills/ntp/html/decode.html#peer
# if host 1 is system peer then it gets value 1.6 

sed $SEDARG < $STATSDIR/${PEERSTATS}.$SELDATE | $AWK '{ print ( $2, $3, $4 ) }' | \
  $AWK '{ print ( $1 , $2 , substr ( $3, 2, 1 ) ) }' | \
  $AWK '{ printf ( "%.4f %.2f \n", $1/3600, $2 + $3/10 ) }' > $LIST

YLABEL='.0 reject  /  .1 x falsetick  /  .3 - outlyer \n.4 + candidate  /  .5 # backup  /  .6 * peer  /  .7 o pps '

gnuplot << EOF
  $STERM
  $FILE
  set title "$TITLE"
  set xlabel "hour"
  set ylabel "$YLABEL" 
  set yrange $YRANGE
  set xtics 1
  set ytics 0.2
  set xrange [-0.5:24.8]
  plot "$LIST" using 1:2 title "$HOSTN - $MYADDR" 
EOF

if test "$DEBUG" == y
  then
    echo plotfile: $LIST
    cat $TMPIPADDR
  else
    rm -f $LIST $TMPIPADDR 
fi

exit 0


